[package]
name = "mithril-end-to-end"
version = "0.2.1"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
default-run = "mithril-end-to-end"

[[bin]]
name = "load-aggregator"
test = false
bench = false

[dependencies]
anyhow = "1.0.71"
async-recursion = "1.0.4"
async-trait = "0.1.52"
clap = { version = "4.0.18", features = ["derive"] }
glob = "0.3"
hex = "0.4.3"
indicatif = { version = "0.17.5", features = ["tokio"] }
mithril-common = { path = "../../mithril-common" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.10"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_trace",
] }
slog-async = "2.7.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"
thiserror = "1.0.31"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.1", features = ["codec"] }

[features]
default = []
portable = ["mithril-common/portable"]
allow_skip_signer_certification = []
