[package]
name = "mithril-aggregator"
version = "0.3.66"
description = "A Mithril Aggregator server"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1.52"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0", features = ["derive", "env", "cargo"] }
cloud-storage = "0.11.0"
config = "0.13.1"
flate2 = "1.0.23"
hex = "0.4.3"
mithril-common = { path = "../mithril-common" }
openssl = { version = "*", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
reqwest = { version = "0.11", features = ["json"] }
semver = "1.0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.10"
sha2 = "0.10.2"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.7.0"
slog-bunyan = "2.4.0"
slog-scope = "4.4.0"
sqlite = { version = "0.31.0", features = ["bundled"] }
tar = "0.4.38"
thiserror = "1.0.31"
tokio = { version = "1.17.0", features = ["full"] }
tokio-util = { version = "0.7.1", features = ["codec"] }
typetag = "0.2.8"
uuid = { version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
warp = "0.3"

[dev-dependencies]
httpmock = "0.6.6"
mithril-common = { path = "../mithril-common", features = [
    "allow_skip_signer_certification",
] }
mockall = "0.11.0"
slog-term = "2.9.0"
tempfile = "3.3.0"

[features]
portable = [
    "mithril-common/portable",
] # portable feature avoids SIGILL crashes on CPUs not supporting Intel ADX instruction set when built on CPUs that support it
bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
