[package]
name = "mithril-client"
version = "0.3.3"
description = "A Mithril Client"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
async-recursion = "1.0.4"
async-trait = "0.1.52"
clap = { version = "4.0", features = ["derive", "env"] }
cli-table = "0.4"
config = "0.13.1"
directories = "4.0.1"
flate2 = "1.0.23"
futures = "0.3"
hex = "0.4.3"
human_bytes = { version = "0.4.2", features = ["fast"] }
mithril-common = { path = "../mithril-common" }
reqwest = { version = "0.11", features = ["json", "stream"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.7.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"
tar = "0.4.38"
thiserror = "1.0.31"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
httpmock = "0.6.6"
mithril-common = { path = "../mithril-common" }
mockall = "0.11.0"

[features]
portable = ["mithril-common/portable"]
