name: Docker Image CI

on:
  workflow_dispatch:
  
env:
  build_tag: 2327.0-pre

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.build_tag }}
        
    - name: Build the Docker image
      run: docker build . --file mithril-signer/Dockerfile \
        --tag ghcr.io/chaincrucial/mithril-signer:${{ env.build_tag }} \
        --tag ghcr.io/chaincrucial/mithril-signer:latest
        
    - name: Push the Docker image
      run: docker push ghcr.io/chaincrucial/mithril-signer:${{ env.build_tag }}
        docker push ghcr.io/chaincrucial/mithril-signer:latest
      
