name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to be released
        required: true
      prerelease:
        description: Is the release a pre releae?
        type: boolean
        required: false
        default: false
      registry:
        description: The registry to push the image to
        type: string
        required: false
        default: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag the Docker image
      run: |
        docker build . --file mithril-signer/Dockerfile --tag ghcr.io/chaincrucial/mithril-signer:${{ inputs.tag }}
        docker tag ghcr.io/chaincrucial/mithril-signer:${{ inputs.tag }} ghcr.io/chaincrucial/mithril-signer:latest
        
    - name: Push the Docker image
      run: |
        docker push ghcr.io/chaincrucial/mithril-signer:${{ inputs.tag }}
        docker push ghcr.io/chaincrucial/mithril-signer:latest
      
