name: Docker Image CI

on:
  workflow_dispatch:
  
env:
  build_tag: "2329.0"
  registry: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ env.build_tag }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag the Docker image
      run: |
        docker build . --file mithril-signer/Dockerfile --tag ghcr.io/chaincrucial/mithril-signer:${{ env.build_tag }}
        docker tag ghcr.io/chaincrucial/mithril-signer:${{ env.build_tag }} ghcr.io/chaincrucial/mithril-signer:latest
        
    - name: Push the Docker image
      run: |
        docker push ghcr.io/chaincrucial/mithril-signer:${{ env.build_tag }}
        docker push ghcr.io/chaincrucial/mithril-signer:latest
      
